export const students = [
  {
    id: 1,
    first_name: "asdf",
    last_name: "Sultan",
    gender: "M",
    age: 35,
    contact_add: "639 113 32 43",
    stud_email: "rsultan0@phoca.cz",
    stud_pass: "h4RmmdG",
  },
  {
    id: 2,
    first_name: "Molly",
    gender: "F",
    last_name: "Penvarden",
    age: 33,
    contact_add: "639 113 32 43",
    stud_email: "mpenvarden1@usa.gov",
    stud_pass: "BVmtq7oIXFu3",
  },
  {
    id: 3,
    first_name: "Peggie",
    last_name: "Batten",
    gender: "F",
    age: 26,
    contact_add: "639 113 32 43",
    stud_email: "pbatten2@oakley.com",
    stud_pass: "m7kKcQzUIgr",
  },
  {
    id: 4,
    first_name: "Celie",
    last_name: "Harry",
    gender: "F",
    age: 19,
    contact_add: "639 113 32 43",
    stud_email: "charry3@linkedin.com",
    stud_pass: "icUTKIH",
  },
  {
    id: 5,
    first_name: "Menard",
    last_name: "MacCawley",
    gender: "M",
    age: 29,
    contact_add: "639 113 32 43",
    stud_email: "mmaccawley4@mit.edu",
    stud_pass: "hDxXgw3aURP",
  },
];
